### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by Ep8Script** [CTCaer/jc_toolkit#18]
Hey, this shouldn't be here but I can't access GBATemp or build this atm. Would you be able to maybe put up a build, even temporarily? It'd help me use it and test it out as I won't be able to build it for like another 5 hours (on my super slow laptop :( ). Much appreciated!

If you don't want to upload it anywhere here, you can send it to *removed for privacy*, that should work. Thanks!

**Comment by CTCaer** [comment]
Thanks
For anyone that want a current build, until I release a final version, it can be found here:
https://mega.nz/#!VYVyjCrY!un7M4EkDSB7un1YwYyF5HwlToW1xZYgSKjTA-IsXOTA

**Comment by CTCaer** [comment]
v5.0.0 release version is out
