### ISSUE TITLE
Right Joycon X-X

### ISSUE THREAD

**Issue by Alexzandro** [CTCaer/jc_toolkit#20]
When I'm trying to change the right joycon's color, it keeps saying that I need to push a button for it to reconnect when its connected, I try to repair it and it keeps coming up with that

**Comment by CTCaer** [comment]
What jc toolkit version you used? Windows version?
Bluetooth stack (microsoft/toshiba/cypress/etc)?

There was another one that had the same problem.

He could connect to the controller, and open the app, but nothing else.
And also he could press buttons and show up in the controller settings in Windows.

I still believe there's something wrong with the drivers initialization from windows when this happens.

My app after opening it, when you try to do a function, it tries to reopen the hid handle to the joy-con, to make sure that it's still connected. If it fails, it shows this message.

I believe that sth takes full control of the handle and does not let the app to connect again..
Btw, if you close the app and open it, it shows up? colors/SN/mac/etc?

**Comment by Alexzandro** [comment]
I am using the 5.0 version with a windows 10 laptop manufactured by HP. It does show the serial number, mac address and its default color when manufactured and it is the same when I re-open it.

Heres what it says with this picture I had attached and the Home button flashes its secret blue light that many people know about now.

![image](https://user-images.githubusercontent.com/38173554/38763445-a5885a9e-3f50-11e8-8f87-83530f8e976b.png)

**Comment by CTCaer** [comment]
So it fails to re-open the hid handle at 
https://github.com/CTCaer/jc_toolkit/blob/master/jctool/jctool.cpp#L2758

I think that sth happens when it fails (as it should) to connect to a left joy-con and then tries to connect to a right joy-con.
Maybe I should put a small delay there for cases like yours.

Try this version:
[jctest.zip](https://github.com/CTCaer/jc_toolkit/files/1910092/jctest.zip)

I've added 15ms delay between the controller exists checks and also some debug printing

**Comment by CTCaer** [comment]
By the way, you use the Microsoft BT stack? 
If yes, your BT adapter name should be **Generic Bluetooth Radio** or **Adapter** in **Device Manager**.
(Not in Settings->devices. There should have the real model.)

**Comment by Alexzandro** [comment]
I tried the one with the 15 milisecond delay and this still happened
![image](https://user-images.githubusercontent.com/38173554/38848672-22a8d6a2-41bd-11e8-84bd-82e86cc34ba7.png)
Plus, I dont really think I'm using microsoft bt stack.
![image](https://user-images.githubusercontent.com/38173554/38848731-7698620a-41bd-11e8-9973-89881969ca68.png)

**Comment by CTCaer** [comment]
The drivers are intel, but are based on the Microsoft bt stack. You can see the Microsoft bluetooth sub-devices below it.

I don't understand why that happens. It's like the controller disappears or the app takes exclusive usage. But in windows you can't do that in user mode. And my app does not work in kernel mode hid.

I will send you another revision. A special build that will not check for connectivity after connecting the first time.
If this will work, I'll make a command line option for cases like yours.

I'll upload a build here in the next 3-5 hours.

**Comment by CTCaer** [comment]
Please check the following build:
[jctest2.zip](https://github.com/CTCaer/jc_toolkit/files/1920991/jctest2.zip)

You need to run *disable_connection_check.bat*

If this works, I'll add it to the next release.

This basically does not check the connection status by trying to open the HID device handle again.
So if the device get's disconnected for any reason, the app will hang or the operation will fail.

**Comment by Alexzandro** [comment]
It worked!!!!! Thank you so much!!!

**Comment by CTCaer** [comment]
Feature for this edge case was added in v5.2.0

Thanks @Alexzandro for testing

**Comment by dangkness** [comment]
Hi CTCaer Love your application for changing the color of my custom joycons, but I am having the exact same problem as @Alexzandro. I am running version JC Toolkit Ver. 5.2.0 on windows 10. I get the exact same error message that the right joycon has been disconnected. I'm able to open the program and it shows all of the SN, MAC, and FW version, but after that I'm not able to do anything I cant view the IR camera I cant change the colors. The exact same issue Alexzandro was having, the left works fine, the right does not.

**Comment by mmemem** [comment]
hey my right joy con says the device was disconnect press a button to try again how do i do it

**Comment by mattLove06** [comment]
Hey there @dangkness , I made this comment in your sub-thread, but I figure I'll post it here too for anybody else having the same issue:
I recently downloaded @CTCaer 's Joy-Con Toolkit, and ran into the same problem with my right Joy-Con as many other people did. I figured out that the disable_connection_check.bat file is included in the v5.2.0 release as @CTCaer said it would be, it just doesn't run itself automatically.
If you are having the right Joy-Con problem, you can find the disable_connection_check.bat file in the debug_scripts folder. Just open it while you have your Joy-Con connected to your computer, and the toolkit should open and you'll be able to back up your SPI and write colors to your controller. For me the refresh and disconnect buttons were both disabled when I open it this way, but hopefully that's not too bothersome for you.
I hope this comment helps anybody in the future looking for an answer, and spares some people from having to go through all the steps I did, only to figure it out it was sitting in the debug folder all along.
