### ISSUE TITLE
Running on Parallels

### ISSUE THREAD

**Issue by XeroShi** [CTCaer/jc_toolkit#21]
The joycon connected but the tool kit did not even recognize the the right joycon that was connected.

**Comment by UlyssesWu** [comment]
~~Duplicate of ♯5~~

I misunderstood your issue. Sorry!

**Comment by XeroShi** [comment]
>Currently it does not support dual joy-con.
Add icon-based selector.
Add dual joy-con button test
Add usb support?
I'm only using One joycon. I'm Using VMware though.

**Comment by CTCaer** [comment]
Try the -f command line option.
The problem probably originates from VMware, but to make sure, check that you have the microsoft bluetooth stack on the guest OS
