### ISSUE TITLE
how to produce *.bnvib file

### ISSUE THREAD

**Issue by forrestDun** [CTCaer/jc_toolkit#25]
Hi CTCaer, I just wonder is there any means to produce *.bnvib file from wav file? I expect getting your help.

**Comment by CTCaer** [comment]
nothing public unfortunately

I have a midi to bnvib but it does work with specific frequencies. So, I don't intend to work on it and release it.

**Comment by TheSwiftTiger** [comment]
hey, if you still have the program could I take a look at it? I'm trying to make a midi to bnvib program myself and it'd be so much easier if I had something to work off of
