### ISSUE TITLE
Mac version

### ISSUE THREAD

**Issue by jasonrebe** [CTCaer/jc_toolkit#29]
Can you make a mac version of joycon toolkit

**Comment by CTCaer** [comment]
Unfortunately no. It's too big of a task to do, because the whole UI is tied to net framework

**Comment by jasonrebe** [comment]
can you try making this in Swift on a Mac.

**Comment by CTCaer** [comment]
Nope.
If anyone is willing to do it, I can only help on problem.

**Comment by jasonrebe** [comment]
if I used Xcode to design the layout and you do the code, you should have Xcode installed on a Mac.
