### ISSUE TITLE
FormJoy.h spelling mistake

### ISSUE THREAD

**Issue by Ep8Script** [CTCaer/jc_toolkit#3]
On line 2033, "writen" should be "written".

Obviously minor so take it as you will.

**Comment by CTCaer** [comment]
Thanks. Fixed internally. Can you spot anything else?

**Comment by Ep8Script** [comment]
I'll have a look around at some point. That one just stood out to me. Keep up the good work!

**Comment by CTCaer** [comment]
If you find anything else, please feel free to reopen this issue
