### ISSUE TITLE
Ability to update joycon firmware

### ISSUE THREAD

**Issue by jasonrebe** [CTCaer/jc_toolkit#30]
Can you add a feature to update the switch joycon firmware. The application will connect to nintendo servers to check for new firmware and install it.

**Comment by CTCaer** [comment]
This can't be done, because it needs kernel drivers in order to accomplish that and a redesign of the protocol.

**Comment by jasonrebe** [comment]
can you release kernel drivers to update the Joycon firmware

**Comment by CTCaer** [comment]
Nope, no time for that.
