### ISSUE TITLE
Releases don't contain built executable (Windows)

### ISSUE THREAD

**Issue by ValliantStorme** [CTCaer/jc_toolkit#8]
It's common practice to release full builds alongside the source when doing a release. Just spent a lot of time with someone because they couldn't find the release binary.

GBATemp is nice, but having the source and the binary in the same place is even better.

**Comment by CTCaer** [comment]
Normally that's the case.
But I decided to separate them for 2 reasons.
1. Github does not provide basic download analytics (e.g. download count)
2. The source in github is for people who want to learn how everything works and delve on the insides and experiment or even copy/improve and incorporate it inside their code.

So until further notice, I will keep the binary releases in GBATemp.
(I'll add info in readme though, for less confusion)

**Comment by ValliantStorme** [comment]
Thank you!
