### ISSUE TITLE
Pro controller button resets to white on write.

### ISSUE THREAD

**Issue by trainboy2019** [CTCaer/jc_toolkit#9]
Whenever I try to change a pro controllers button color, it always resets to white. Even if I use one of the stock colors.

**Comment by CTCaer** [comment]
Is it possible to use the following (I don't have a Pro controller):
http://desowin.org/usbpcap/
and capture some packets so I can check what's happening?

The procedure is the following:
1. Install USBPCap and restart
2. After the restart you will see the usb drivers re-installing them selves. Wait a bit for all of them.
3. After this is done open JC Toolkit and change the colors and wait. Don't hit "Write Colors" yet!.
4. Run USBPcapCMD.exe from C:\Program Files\USBPcap
5. Write the number of the usb hub that includes the port that your BT adapter is and hit enter.
6. write a name for the file. e.g. test.pcap and hit enter
7. It will ask you if you want to allow it, select yes.
8. The usb packet capturing will start. Hit "Write Colors" in the app
9. After it's done, go to the USBPcap console and press CTRL+C

Send me the .pcap file to my email. You can find it in my GitHub profile.

**Comment by trainboy2019** [comment]
I sent the email

**Comment by CTCaer** [comment]
Thank you for the time you invested!
It helps me a lot to understand the Pro controller behavior.

The colors you tried were
```
Body:    a6 28 ff
Buttons: 56 cd 46
```
Correct?

So what I see is a strange behavior. 
Your controller replies back that it got the write commands, but the address and size are zeroed..

Also another thing I saw is that it constantly sends button state data. But as I can see, you don't press any button or play with the sticks. So maybe this is normal for Pro controller. Anyway, it's not a big issue though.

Anyway, I'll fully examine your file and compare with one from my  Joy-Con later.

**Comment by trainboy2019** [comment]
I'm glad I was able to help, yes those were the colors I was setting. If you need any more info, feel free to ask.

**Comment by CTCaer** [comment]
Yes, the grey buttons in v2.5.1 for the FF FF FF values was by design. 
The algorithm I was using to paint the controller, was producing many unwanted white spots.

You can check the improvement in quality, by opening v2.5.1 and v3.0.1 side by side.
Choose, 254,254,254 for v2.5.1 to bypass my code and check how it looks versus v3.0.1.
One word for v2.5.1 quality: crap.

**Comment by CTCaer** [comment]
@trainboy2019 
Try this please:
https://mega.nz/#!ZQcRHBxB!J1U-QDdFBAbDuA8-lQyrJ9BBSiwS2zAa6evyLvsdn1c

**Comment by trainboy2019** [comment]
It works!

**Comment by CTCaer** [comment]
Nice to hear! Seams that the mitigation works.
One last request to you, is it possible to capture one more USBPcap file?

Now I need to check the whole procedure:
Open USBPcap before opening the app and start capturing.
Open JC toolkit, choose colors, write them, close USBPcap.

**Comment by CTCaer** [comment]
Fixed!
